server:
  port: ${PORT:8080}
spring:
  main:
    banner-mode: log

tcsbroker:
  url: https://api-invest.tinkoff.ru/openapi/

bot:
  name: AnalizePortfolioInvestmentBot
  token: 1663649822:AAGtb9BEfZh6Vaz0FXq9uKSLFcWk9EhI4z4